version: '3.4'
services:
  jaeger:
   container_name: "jaeger-container"
   ports:
    - 4317:4317
    - 4318:4318
    - 16686:16686
  zipkin: 
   container_name: "zipkin-container"
   ports:
    - 9411:9411